### ISSUE TITLE
What to do with these?

### ISSUE THREAD

**Issue by Publo256** [badewen/Growtopia-Dumps#1]
What to do with those dumps? 
Where are they used for?

**Comment by badewen** [comment]
well you see, growtopia is packed with vmprotect and it makes it almost impossible to reverse engineer it. and that's where these dumps are used. You can reverse engineer these dump as it resemble the original executable after getting unpacked in the runtime by vmprotect. Although i cant confirm that it 100% matches the original. 

TL;DR : These dumps can be used for Static Code Analysis.
